name: Build Unsigned IPA for iOS

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build-ios-unsigned:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm ci

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
        shell: bash

      - name: Build iOS app (unsigned)
        run: |
          npm run ios:build:unsigned || npx react-native run-ios --configuration Release --no-packager || echo 'Customize this step to match your project'
        env:
          CI: true

      - name: Archive app to IPA (unsigned)
        run: |
          cd ios
          xcodebuild -workspace TrueControl.xcworkspace \
            -scheme TrueControl \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/TrueControl.xcarchive archive
          xcodebuild -exportArchive \
            -archivePath $PWD/build/TrueControl.xcarchive \
            -exportOptionsPlist ExportOptions-unsigned.plist \
            -exportPath $PWD/build/ipa-unsigned
        shell: bash

      - name: Upload unsigned IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: ios/build/ipa-unsigned/*.ipa

      - name: Show IPA location
        run: |
          echo "The unsigned IPA is available in ios/build/ipa-unsigned/"

# You may need to adjust scheme/workspace names and add an ExportOptions-unsigned.plist file.
# Example ExportOptions-unsigned.plist:
# <?xml version="1.0" encoding="UTF-8"?>
# <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
# <plist version="1.0">
# <dict>
#   <key>method</key>
#   <string>ad-hoc</string>
#   <key>signingStyle</key>
#   <string>manual</string>
#   <key>compileBitcode</key>
#   <false/>
#   <key>signingCertificate</key>
#   <string></string>
#   <key>provisioningProfiles</key>
#   <dict/>
# </dict>
# </plist>
